/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common.pb-c.h"
void   empty_request__init
                     (EmptyRequest         *message)
{
  static const EmptyRequest init_value = EMPTY_REQUEST__INIT;
  *message = init_value;
}
size_t empty_request__get_packed_size
                     (const EmptyRequest *message)
{
  assert(message->base.descriptor == &empty_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t empty_request__pack
                     (const EmptyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &empty_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t empty_request__pack_to_buffer
                     (const EmptyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &empty_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EmptyRequest *
       empty_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EmptyRequest *)
     protobuf_c_message_unpack (&empty_request__descriptor,
                                allocator, len, data);
}
void   empty_request__free_unpacked
                     (EmptyRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &empty_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ret_response__init
                     (RetResponse         *message)
{
  static const RetResponse init_value = RET_RESPONSE__INIT;
  *message = init_value;
}
size_t ret_response__get_packed_size
                     (const RetResponse *message)
{
  assert(message->base.descriptor == &ret_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ret_response__pack
                     (const RetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ret_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ret_response__pack_to_buffer
                     (const RetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ret_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RetResponse *
       ret_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RetResponse *)
     protobuf_c_message_unpack (&ret_response__descriptor,
                                allocator, len, data);
}
void   ret_response__free_unpacked
                     (RetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ret_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define empty_request__field_descriptors NULL
#define empty_request__field_indices_by_name NULL
#define empty_request__number_ranges NULL
const ProtobufCMessageDescriptor empty_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EmptyRequest",
  "EmptyRequest",
  "EmptyRequest",
  "",
  sizeof(EmptyRequest),
  0,
  empty_request__field_descriptors,
  empty_request__field_indices_by_name,
  0,  empty_request__number_ranges,
  (ProtobufCMessageInit) empty_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ret_response__field_descriptors[1] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RetResponse, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ret_response__field_indices_by_name[] = {
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange ret_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ret_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RetResponse",
  "RetResponse",
  "RetResponse",
  "",
  sizeof(RetResponse),
  1,
  ret_response__field_descriptors,
  ret_response__field_indices_by_name,
  1,  ret_response__number_ranges,
  (ProtobufCMessageInit) ret_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
