/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

#ifndef PROTOBUF_C_common_2eproto__INCLUDED
#define PROTOBUF_C_common_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct EmptyRequest EmptyRequest;
typedef struct RetResponse RetResponse;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @brief Request without parameters.
 */
struct  EmptyRequest
{
  ProtobufCMessage base;
};
#define EMPTY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&empty_request__descriptor) \
 }


/*
 **
 * @brief Response carrying only a return code.
 * @param ret Return code (0 on success, < 0 on error)
 */
struct  RetResponse
{
  ProtobufCMessage base;
  int32_t ret;
};
#define RET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ret_response__descriptor) \
, 0 }


/* EmptyRequest methods */
void   empty_request__init
                     (EmptyRequest         *message);
size_t empty_request__get_packed_size
                     (const EmptyRequest   *message);
size_t empty_request__pack
                     (const EmptyRequest   *message,
                      uint8_t             *out);
size_t empty_request__pack_to_buffer
                     (const EmptyRequest   *message,
                      ProtobufCBuffer     *buffer);
EmptyRequest *
       empty_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   empty_request__free_unpacked
                     (EmptyRequest *message,
                      ProtobufCAllocator *allocator);
/* RetResponse methods */
void   ret_response__init
                     (RetResponse         *message);
size_t ret_response__get_packed_size
                     (const RetResponse   *message);
size_t ret_response__pack
                     (const RetResponse   *message,
                      uint8_t             *out);
size_t ret_response__pack_to_buffer
                     (const RetResponse   *message,
                      ProtobufCBuffer     *buffer);
RetResponse *
       ret_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ret_response__free_unpacked
                     (RetResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*EmptyRequest_Closure)
                 (const EmptyRequest *message,
                  void *closure_data);
typedef void (*RetResponse_Closure)
                 (const RetResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor empty_request__descriptor;
extern const ProtobufCMessageDescriptor ret_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_common_2eproto__INCLUDED */
