/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: priv_access.proto */

#ifndef PROTOBUF_C_priv_5faccess_2eproto__INCLUDED
#define PROTOBUF_C_priv_5faccess_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "common.pb-c.h"

typedef struct RndAddToEntCntRequest RndAddToEntCntRequest;
typedef struct RndAddEntropyRequest RndAddEntropyRequest;
typedef struct SetWriteWakeupThreshRequest SetWriteWakeupThreshRequest;
typedef struct SetMinReseedSecsRequest SetMinReseedSecsRequest;
typedef struct SetPkcs11ConfigRequest SetPkcs11ConfigRequest;
typedef struct SelftestResponse SelftestResponse;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @brief Request to change the entropy estimator of the ES manager
 * @param entcnt Entropy value in bits to set to (value is capped to maximum
 *		 possible entropy value)
 */
struct  RndAddToEntCntRequest
{
  ProtobufCMessage base;
  uint32_t entcnt;
};
#define RND_ADD_TO_ENT_CNT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rnd_add_to_ent_cnt_request__descriptor) \
, 0 }


/*
 **
 * @brief Request to add data to the auxiliary entropy pool and increase the
 *	  pool's entropy estimate accordingly
 * @param randval Buffer with the entropy data
 * @param entcnt Entropy value in bits to set to (value is capped to maximum
 *		 possible entropy value)
 */
struct  RndAddEntropyRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData randval;
  uint32_t entcnt;
};
#define RND_ADD_ENTROPY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rnd_add_entropy_request__descriptor) \
, {0,NULL}, 0 }


/*
 **
 * @brief Request to set the available write wakeup threshold
 */
struct  SetWriteWakeupThreshRequest
{
  ProtobufCMessage base;
  uint32_t wakeup;
};
#define SET_WRITE_WAKEUP_THRESH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&set_write_wakeup_thresh_request__descriptor) \
, 0 }


/*
 **
 * @brief Request to set the available write wakeup threshold
 */
struct  SetMinReseedSecsRequest
{
  ProtobufCMessage base;
  uint32_t seconds;
};
#define SET_MIN_RESEED_SECS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&set_min_reseed_secs_request__descriptor) \
, 0 }


/*
 **
 * @brief Request to update the runtime configuration of the PKCS#11 entropy
 *	  source.
 * Each field is only applied when its corresponding `set_*` flag is true,
 * which lets callers update only the PIN, only the label, or both atomically.
 * Update order on the server: the token label is applied first (it re-opens
 * the PKCS#11 module against the new label), then the PIN is installed and
 * a login is attempted on the freshly opened slot if the token requires it.
 * If the label update fails, the PIN is not applied.
 * Passing the empty string for `pin` or `token_label` (with the matching
 * `set_*` flag set) clears the runtime override and falls back to the
 * compile-time default.
 * The settings are in-memory only and are not persisted across server
 * restarts.
 * @param set_token_label Apply `token_label` if true.
 * @param token_label PKCS#11 token label to select.
 * @param set_pin Apply `pin` if true.
 * @param pin User PIN to authenticate with the PKCS#11 token (CKU_USER).
 */
struct  SetPkcs11ConfigRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean set_token_label;
  char *token_label;
  protobuf_c_boolean set_pin;
  char *pin;
};
#define SET_PKCS11_CONFIG_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&set_pkcs11_config_request__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/*
 **
 * @brief Response reporting the outcome of the self tests.
 * The two states carry the values the ESDM uses internally and reports in its
 * status: 0 - the test has not run, 1 - it passed, 2 - it failed. They are
 * separate because they mean different things: a failed crypto self test stops
 * the ESDM from handing out random bits, while a failed entropy source is one
 * of several and only stops being credited.
 * @param ret 0 if every self test passed and the ESDM hands out random bits,
 *	      < 0 otherwise - the error of the failing test, or -EOPNOTSUPP
 *	      where an earlier self test failed and still holds the output back
 * @param crypto_state State of the self tests of the hash and the DRNG
 * @param es_state State of the self tests of the entropy sources
 * @param es_sources Number of entropy sources the pass tested
 * @param es_failures Number of entropy sources that failed their self test
 */
struct  SelftestResponse
{
  ProtobufCMessage base;
  int32_t ret;
  uint32_t crypto_state;
  uint32_t es_state;
  uint32_t es_sources;
  uint32_t es_failures;
};
#define SELFTEST_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&selftest_response__descriptor) \
, 0, 0, 0, 0, 0 }


/* RndAddToEntCntRequest methods */
void   rnd_add_to_ent_cnt_request__init
                     (RndAddToEntCntRequest         *message);
size_t rnd_add_to_ent_cnt_request__get_packed_size
                     (const RndAddToEntCntRequest   *message);
size_t rnd_add_to_ent_cnt_request__pack
                     (const RndAddToEntCntRequest   *message,
                      uint8_t             *out);
size_t rnd_add_to_ent_cnt_request__pack_to_buffer
                     (const RndAddToEntCntRequest   *message,
                      ProtobufCBuffer     *buffer);
RndAddToEntCntRequest *
       rnd_add_to_ent_cnt_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rnd_add_to_ent_cnt_request__free_unpacked
                     (RndAddToEntCntRequest *message,
                      ProtobufCAllocator *allocator);
/* RndAddEntropyRequest methods */
void   rnd_add_entropy_request__init
                     (RndAddEntropyRequest         *message);
size_t rnd_add_entropy_request__get_packed_size
                     (const RndAddEntropyRequest   *message);
size_t rnd_add_entropy_request__pack
                     (const RndAddEntropyRequest   *message,
                      uint8_t             *out);
size_t rnd_add_entropy_request__pack_to_buffer
                     (const RndAddEntropyRequest   *message,
                      ProtobufCBuffer     *buffer);
RndAddEntropyRequest *
       rnd_add_entropy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rnd_add_entropy_request__free_unpacked
                     (RndAddEntropyRequest *message,
                      ProtobufCAllocator *allocator);
/* SetWriteWakeupThreshRequest methods */
void   set_write_wakeup_thresh_request__init
                     (SetWriteWakeupThreshRequest         *message);
size_t set_write_wakeup_thresh_request__get_packed_size
                     (const SetWriteWakeupThreshRequest   *message);
size_t set_write_wakeup_thresh_request__pack
                     (const SetWriteWakeupThreshRequest   *message,
                      uint8_t             *out);
size_t set_write_wakeup_thresh_request__pack_to_buffer
                     (const SetWriteWakeupThreshRequest   *message,
                      ProtobufCBuffer     *buffer);
SetWriteWakeupThreshRequest *
       set_write_wakeup_thresh_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   set_write_wakeup_thresh_request__free_unpacked
                     (SetWriteWakeupThreshRequest *message,
                      ProtobufCAllocator *allocator);
/* SetMinReseedSecsRequest methods */
void   set_min_reseed_secs_request__init
                     (SetMinReseedSecsRequest         *message);
size_t set_min_reseed_secs_request__get_packed_size
                     (const SetMinReseedSecsRequest   *message);
size_t set_min_reseed_secs_request__pack
                     (const SetMinReseedSecsRequest   *message,
                      uint8_t             *out);
size_t set_min_reseed_secs_request__pack_to_buffer
                     (const SetMinReseedSecsRequest   *message,
                      ProtobufCBuffer     *buffer);
SetMinReseedSecsRequest *
       set_min_reseed_secs_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   set_min_reseed_secs_request__free_unpacked
                     (SetMinReseedSecsRequest *message,
                      ProtobufCAllocator *allocator);
/* SetPkcs11ConfigRequest methods */
void   set_pkcs11_config_request__init
                     (SetPkcs11ConfigRequest         *message);
size_t set_pkcs11_config_request__get_packed_size
                     (const SetPkcs11ConfigRequest   *message);
size_t set_pkcs11_config_request__pack
                     (const SetPkcs11ConfigRequest   *message,
                      uint8_t             *out);
size_t set_pkcs11_config_request__pack_to_buffer
                     (const SetPkcs11ConfigRequest   *message,
                      ProtobufCBuffer     *buffer);
SetPkcs11ConfigRequest *
       set_pkcs11_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   set_pkcs11_config_request__free_unpacked
                     (SetPkcs11ConfigRequest *message,
                      ProtobufCAllocator *allocator);
/* SelftestResponse methods */
void   selftest_response__init
                     (SelftestResponse         *message);
size_t selftest_response__get_packed_size
                     (const SelftestResponse   *message);
size_t selftest_response__pack
                     (const SelftestResponse   *message,
                      uint8_t             *out);
size_t selftest_response__pack_to_buffer
                     (const SelftestResponse   *message,
                      ProtobufCBuffer     *buffer);
SelftestResponse *
       selftest_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   selftest_response__free_unpacked
                     (SelftestResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RndAddToEntCntRequest_Closure)
                 (const RndAddToEntCntRequest *message,
                  void *closure_data);
typedef void (*RndAddEntropyRequest_Closure)
                 (const RndAddEntropyRequest *message,
                  void *closure_data);
typedef void (*SetWriteWakeupThreshRequest_Closure)
                 (const SetWriteWakeupThreshRequest *message,
                  void *closure_data);
typedef void (*SetMinReseedSecsRequest_Closure)
                 (const SetMinReseedSecsRequest *message,
                  void *closure_data);
typedef void (*SetPkcs11ConfigRequest_Closure)
                 (const SetPkcs11ConfigRequest *message,
                  void *closure_data);
typedef void (*SelftestResponse_Closure)
                 (const SelftestResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct PrivAccess_Service PrivAccess_Service;
struct PrivAccess_Service
{
  ProtobufCService base;
  void (*rpc_rnd_add_to_ent_cnt)(PrivAccess_Service *service,
                                 const RndAddToEntCntRequest *input,
                                 RetResponse_Closure closure,
                                 void *closure_data);
  void (*rpc_rnd_add_entropy)(PrivAccess_Service *service,
                              const RndAddEntropyRequest *input,
                              RetResponse_Closure closure,
                              void *closure_data);
  void (*rpc_rnd_clear_pool)(PrivAccess_Service *service,
                             const EmptyRequest *input,
                             RetResponse_Closure closure,
                             void *closure_data);
  void (*rpc_rnd_reseed_crng)(PrivAccess_Service *service,
                              const EmptyRequest *input,
                              RetResponse_Closure closure,
                              void *closure_data);
  void (*rpc_set_write_wakeup_thresh)(PrivAccess_Service *service,
                                      const SetWriteWakeupThreshRequest *input,
                                      RetResponse_Closure closure,
                                      void *closure_data);
  void (*rpc_set_min_reseed_secs)(PrivAccess_Service *service,
                                  const SetMinReseedSecsRequest *input,
                                  RetResponse_Closure closure,
                                  void *closure_data);
  void (*rpc_set_pkcs11_config)(PrivAccess_Service *service,
                                const SetPkcs11ConfigRequest *input,
                                RetResponse_Closure closure,
                                void *closure_data);
  void (*rpc_selftest)(PrivAccess_Service *service,
                       const EmptyRequest *input,
                       SelftestResponse_Closure closure,
                       void *closure_data);
};
typedef void (*PrivAccess_ServiceDestroy)(PrivAccess_Service *);
void priv_access__init (PrivAccess_Service *service,
                        PrivAccess_ServiceDestroy destroy);
#define PRIV_ACCESS__BASE_INIT \
    { &priv_access__descriptor, protobuf_c_service_invoke_internal, NULL }
#define PRIV_ACCESS__INIT(function_prefix__) \
    { PRIV_ACCESS__BASE_INIT,\
      function_prefix__ ## rpc_rnd_add_to_ent_cnt,\
      function_prefix__ ## rpc_rnd_add_entropy,\
      function_prefix__ ## rpc_rnd_clear_pool,\
      function_prefix__ ## rpc_rnd_reseed_crng,\
      function_prefix__ ## rpc_set_write_wakeup_thresh,\
      function_prefix__ ## rpc_set_min_reseed_secs,\
      function_prefix__ ## rpc_set_pkcs11_config,\
      function_prefix__ ## rpc_selftest  }
void priv_access__rpc_rnd_add_to_ent_cnt(ProtobufCService *service,
                                         const RndAddToEntCntRequest *input,
                                         RetResponse_Closure closure,
                                         void *closure_data);
void priv_access__rpc_rnd_add_entropy(ProtobufCService *service,
                                      const RndAddEntropyRequest *input,
                                      RetResponse_Closure closure,
                                      void *closure_data);
void priv_access__rpc_rnd_clear_pool(ProtobufCService *service,
                                     const EmptyRequest *input,
                                     RetResponse_Closure closure,
                                     void *closure_data);
void priv_access__rpc_rnd_reseed_crng(ProtobufCService *service,
                                      const EmptyRequest *input,
                                      RetResponse_Closure closure,
                                      void *closure_data);
void priv_access__rpc_set_write_wakeup_thresh(ProtobufCService *service,
                                              const SetWriteWakeupThreshRequest *input,
                                              RetResponse_Closure closure,
                                              void *closure_data);
void priv_access__rpc_set_min_reseed_secs(ProtobufCService *service,
                                          const SetMinReseedSecsRequest *input,
                                          RetResponse_Closure closure,
                                          void *closure_data);
void priv_access__rpc_set_pkcs11_config(ProtobufCService *service,
                                        const SetPkcs11ConfigRequest *input,
                                        RetResponse_Closure closure,
                                        void *closure_data);
void priv_access__rpc_selftest(ProtobufCService *service,
                               const EmptyRequest *input,
                               SelftestResponse_Closure closure,
                               void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rnd_add_to_ent_cnt_request__descriptor;
extern const ProtobufCMessageDescriptor rnd_add_entropy_request__descriptor;
extern const ProtobufCMessageDescriptor set_write_wakeup_thresh_request__descriptor;
extern const ProtobufCMessageDescriptor set_min_reseed_secs_request__descriptor;
extern const ProtobufCMessageDescriptor set_pkcs11_config_request__descriptor;
extern const ProtobufCMessageDescriptor selftest_response__descriptor;
extern const ProtobufCServiceDescriptor priv_access__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_priv_5faccess_2eproto__INCLUDED */
