/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: priv_access.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "priv_access.pb-c.h"
void   rnd_add_to_ent_cnt_request__init
                     (RndAddToEntCntRequest         *message)
{
  static const RndAddToEntCntRequest init_value = RND_ADD_TO_ENT_CNT_REQUEST__INIT;
  *message = init_value;
}
size_t rnd_add_to_ent_cnt_request__get_packed_size
                     (const RndAddToEntCntRequest *message)
{
  assert(message->base.descriptor == &rnd_add_to_ent_cnt_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rnd_add_to_ent_cnt_request__pack
                     (const RndAddToEntCntRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rnd_add_to_ent_cnt_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rnd_add_to_ent_cnt_request__pack_to_buffer
                     (const RndAddToEntCntRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rnd_add_to_ent_cnt_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RndAddToEntCntRequest *
       rnd_add_to_ent_cnt_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RndAddToEntCntRequest *)
     protobuf_c_message_unpack (&rnd_add_to_ent_cnt_request__descriptor,
                                allocator, len, data);
}
void   rnd_add_to_ent_cnt_request__free_unpacked
                     (RndAddToEntCntRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rnd_add_to_ent_cnt_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rnd_add_entropy_request__init
                     (RndAddEntropyRequest         *message)
{
  static const RndAddEntropyRequest init_value = RND_ADD_ENTROPY_REQUEST__INIT;
  *message = init_value;
}
size_t rnd_add_entropy_request__get_packed_size
                     (const RndAddEntropyRequest *message)
{
  assert(message->base.descriptor == &rnd_add_entropy_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rnd_add_entropy_request__pack
                     (const RndAddEntropyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rnd_add_entropy_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rnd_add_entropy_request__pack_to_buffer
                     (const RndAddEntropyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rnd_add_entropy_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RndAddEntropyRequest *
       rnd_add_entropy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RndAddEntropyRequest *)
     protobuf_c_message_unpack (&rnd_add_entropy_request__descriptor,
                                allocator, len, data);
}
void   rnd_add_entropy_request__free_unpacked
                     (RndAddEntropyRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rnd_add_entropy_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_write_wakeup_thresh_request__init
                     (SetWriteWakeupThreshRequest         *message)
{
  static const SetWriteWakeupThreshRequest init_value = SET_WRITE_WAKEUP_THRESH_REQUEST__INIT;
  *message = init_value;
}
size_t set_write_wakeup_thresh_request__get_packed_size
                     (const SetWriteWakeupThreshRequest *message)
{
  assert(message->base.descriptor == &set_write_wakeup_thresh_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_write_wakeup_thresh_request__pack
                     (const SetWriteWakeupThreshRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_write_wakeup_thresh_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_write_wakeup_thresh_request__pack_to_buffer
                     (const SetWriteWakeupThreshRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_write_wakeup_thresh_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetWriteWakeupThreshRequest *
       set_write_wakeup_thresh_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetWriteWakeupThreshRequest *)
     protobuf_c_message_unpack (&set_write_wakeup_thresh_request__descriptor,
                                allocator, len, data);
}
void   set_write_wakeup_thresh_request__free_unpacked
                     (SetWriteWakeupThreshRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_write_wakeup_thresh_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_min_reseed_secs_request__init
                     (SetMinReseedSecsRequest         *message)
{
  static const SetMinReseedSecsRequest init_value = SET_MIN_RESEED_SECS_REQUEST__INIT;
  *message = init_value;
}
size_t set_min_reseed_secs_request__get_packed_size
                     (const SetMinReseedSecsRequest *message)
{
  assert(message->base.descriptor == &set_min_reseed_secs_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_min_reseed_secs_request__pack
                     (const SetMinReseedSecsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_min_reseed_secs_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_min_reseed_secs_request__pack_to_buffer
                     (const SetMinReseedSecsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_min_reseed_secs_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetMinReseedSecsRequest *
       set_min_reseed_secs_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetMinReseedSecsRequest *)
     protobuf_c_message_unpack (&set_min_reseed_secs_request__descriptor,
                                allocator, len, data);
}
void   set_min_reseed_secs_request__free_unpacked
                     (SetMinReseedSecsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_min_reseed_secs_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_pkcs11_config_request__init
                     (SetPkcs11ConfigRequest         *message)
{
  static const SetPkcs11ConfigRequest init_value = SET_PKCS11_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t set_pkcs11_config_request__get_packed_size
                     (const SetPkcs11ConfigRequest *message)
{
  assert(message->base.descriptor == &set_pkcs11_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_pkcs11_config_request__pack
                     (const SetPkcs11ConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_pkcs11_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_pkcs11_config_request__pack_to_buffer
                     (const SetPkcs11ConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_pkcs11_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetPkcs11ConfigRequest *
       set_pkcs11_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetPkcs11ConfigRequest *)
     protobuf_c_message_unpack (&set_pkcs11_config_request__descriptor,
                                allocator, len, data);
}
void   set_pkcs11_config_request__free_unpacked
                     (SetPkcs11ConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_pkcs11_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   selftest_response__init
                     (SelftestResponse         *message)
{
  static const SelftestResponse init_value = SELFTEST_RESPONSE__INIT;
  *message = init_value;
}
size_t selftest_response__get_packed_size
                     (const SelftestResponse *message)
{
  assert(message->base.descriptor == &selftest_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t selftest_response__pack
                     (const SelftestResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &selftest_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t selftest_response__pack_to_buffer
                     (const SelftestResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &selftest_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SelftestResponse *
       selftest_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SelftestResponse *)
     protobuf_c_message_unpack (&selftest_response__descriptor,
                                allocator, len, data);
}
void   selftest_response__free_unpacked
                     (SelftestResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &selftest_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rnd_add_to_ent_cnt_request__field_descriptors[1] =
{
  {
    "entcnt",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RndAddToEntCntRequest, entcnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rnd_add_to_ent_cnt_request__field_indices_by_name[] = {
  0,   /* field[0] = entcnt */
};
static const ProtobufCIntRange rnd_add_to_ent_cnt_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rnd_add_to_ent_cnt_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RndAddToEntCntRequest",
  "RndAddToEntCntRequest",
  "RndAddToEntCntRequest",
  "",
  sizeof(RndAddToEntCntRequest),
  1,
  rnd_add_to_ent_cnt_request__field_descriptors,
  rnd_add_to_ent_cnt_request__field_indices_by_name,
  1,  rnd_add_to_ent_cnt_request__number_ranges,
  (ProtobufCMessageInit) rnd_add_to_ent_cnt_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rnd_add_entropy_request__field_descriptors[2] =
{
  {
    "randval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RndAddEntropyRequest, randval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entcnt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RndAddEntropyRequest, entcnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rnd_add_entropy_request__field_indices_by_name[] = {
  1,   /* field[1] = entcnt */
  0,   /* field[0] = randval */
};
static const ProtobufCIntRange rnd_add_entropy_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rnd_add_entropy_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RndAddEntropyRequest",
  "RndAddEntropyRequest",
  "RndAddEntropyRequest",
  "",
  sizeof(RndAddEntropyRequest),
  2,
  rnd_add_entropy_request__field_descriptors,
  rnd_add_entropy_request__field_indices_by_name,
  1,  rnd_add_entropy_request__number_ranges,
  (ProtobufCMessageInit) rnd_add_entropy_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_write_wakeup_thresh_request__field_descriptors[1] =
{
  {
    "wakeup",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetWriteWakeupThreshRequest, wakeup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_write_wakeup_thresh_request__field_indices_by_name[] = {
  0,   /* field[0] = wakeup */
};
static const ProtobufCIntRange set_write_wakeup_thresh_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_write_wakeup_thresh_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetWriteWakeupThreshRequest",
  "SetWriteWakeupThreshRequest",
  "SetWriteWakeupThreshRequest",
  "",
  sizeof(SetWriteWakeupThreshRequest),
  1,
  set_write_wakeup_thresh_request__field_descriptors,
  set_write_wakeup_thresh_request__field_indices_by_name,
  1,  set_write_wakeup_thresh_request__number_ranges,
  (ProtobufCMessageInit) set_write_wakeup_thresh_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_min_reseed_secs_request__field_descriptors[1] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetMinReseedSecsRequest, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_min_reseed_secs_request__field_indices_by_name[] = {
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange set_min_reseed_secs_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_min_reseed_secs_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetMinReseedSecsRequest",
  "SetMinReseedSecsRequest",
  "SetMinReseedSecsRequest",
  "",
  sizeof(SetMinReseedSecsRequest),
  1,
  set_min_reseed_secs_request__field_descriptors,
  set_min_reseed_secs_request__field_indices_by_name,
  1,  set_min_reseed_secs_request__number_ranges,
  (ProtobufCMessageInit) set_min_reseed_secs_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_pkcs11_config_request__field_descriptors[4] =
{
  {
    "set_token_label",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SetPkcs11ConfigRequest, set_token_label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token_label",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SetPkcs11ConfigRequest, token_label),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_pin",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SetPkcs11ConfigRequest, set_pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pin",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SetPkcs11ConfigRequest, pin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_pkcs11_config_request__field_indices_by_name[] = {
  3,   /* field[3] = pin */
  2,   /* field[2] = set_pin */
  0,   /* field[0] = set_token_label */
  1,   /* field[1] = token_label */
};
static const ProtobufCIntRange set_pkcs11_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor set_pkcs11_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetPkcs11ConfigRequest",
  "SetPkcs11ConfigRequest",
  "SetPkcs11ConfigRequest",
  "",
  sizeof(SetPkcs11ConfigRequest),
  4,
  set_pkcs11_config_request__field_descriptors,
  set_pkcs11_config_request__field_indices_by_name,
  1,  set_pkcs11_config_request__number_ranges,
  (ProtobufCMessageInit) set_pkcs11_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor selftest_response__field_descriptors[5] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SelftestResponse, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crypto_state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SelftestResponse, crypto_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "es_state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SelftestResponse, es_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "es_sources",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SelftestResponse, es_sources),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "es_failures",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SelftestResponse, es_failures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned selftest_response__field_indices_by_name[] = {
  1,   /* field[1] = crypto_state */
  4,   /* field[4] = es_failures */
  3,   /* field[3] = es_sources */
  2,   /* field[2] = es_state */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange selftest_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor selftest_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SelftestResponse",
  "SelftestResponse",
  "SelftestResponse",
  "",
  sizeof(SelftestResponse),
  5,
  selftest_response__field_descriptors,
  selftest_response__field_indices_by_name,
  1,  selftest_response__number_ranges,
  (ProtobufCMessageInit) selftest_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor priv_access__method_descriptors[8] =
{
  { "RpcRndAddToEntCnt", &rnd_add_to_ent_cnt_request__descriptor, &ret_response__descriptor },
  { "RpcRndAddEntropy", &rnd_add_entropy_request__descriptor, &ret_response__descriptor },
  { "RpcRndClearPool", &empty_request__descriptor, &ret_response__descriptor },
  { "RpcRndReseedCRNG", &empty_request__descriptor, &ret_response__descriptor },
  { "RpcSetWriteWakeupThresh", &set_write_wakeup_thresh_request__descriptor, &ret_response__descriptor },
  { "RpcSetMinReseedSecs", &set_min_reseed_secs_request__descriptor, &ret_response__descriptor },
  { "RpcSetPkcs11Config", &set_pkcs11_config_request__descriptor, &ret_response__descriptor },
  { "RpcSelftest", &empty_request__descriptor, &selftest_response__descriptor },
};
const unsigned priv_access__method_indices_by_name[] = {
  1,        /* RpcRndAddEntropy */
  0,        /* RpcRndAddToEntCnt */
  2,        /* RpcRndClearPool */
  3,        /* RpcRndReseedCRNG */
  7,        /* RpcSelftest */
  5,        /* RpcSetMinReseedSecs */
  6,        /* RpcSetPkcs11Config */
  4         /* RpcSetWriteWakeupThresh */
};
const ProtobufCServiceDescriptor priv_access__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "PrivAccess",
  "PrivAccess",
  "PrivAccess",
  "",
  8,
  priv_access__method_descriptors,
  priv_access__method_indices_by_name
};
void priv_access__rpc_rnd_add_to_ent_cnt(ProtobufCService *service,
                                         const RndAddToEntCntRequest *input,
                                         RetResponse_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_rnd_add_entropy(ProtobufCService *service,
                                      const RndAddEntropyRequest *input,
                                      RetResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_rnd_clear_pool(ProtobufCService *service,
                                     const EmptyRequest *input,
                                     RetResponse_Closure closure,
                                     void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_rnd_reseed_crng(ProtobufCService *service,
                                      const EmptyRequest *input,
                                      RetResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_set_write_wakeup_thresh(ProtobufCService *service,
                                              const SetWriteWakeupThreshRequest *input,
                                              RetResponse_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_set_min_reseed_secs(ProtobufCService *service,
                                          const SetMinReseedSecsRequest *input,
                                          RetResponse_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_set_pkcs11_config(ProtobufCService *service,
                                        const SetPkcs11ConfigRequest *input,
                                        RetResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__rpc_selftest(ProtobufCService *service,
                               const EmptyRequest *input,
                               SelftestResponse_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &priv_access__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void priv_access__init (PrivAccess_Service *service,
                        PrivAccess_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &priv_access__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
