/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: unpriv_access.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "unpriv_access.pb-c.h"
void   val_response__init
                     (ValResponse         *message)
{
  static const ValResponse init_value = VAL_RESPONSE__INIT;
  *message = init_value;
}
size_t val_response__get_packed_size
                     (const ValResponse *message)
{
  assert(message->base.descriptor == &val_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t val_response__pack
                     (const ValResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &val_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t val_response__pack_to_buffer
                     (const ValResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &val_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ValResponse *
       val_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ValResponse *)
     protobuf_c_message_unpack (&val_response__descriptor,
                                allocator, len, data);
}
void   val_response__free_unpacked
                     (ValResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &val_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rand_val_response__init
                     (RandValResponse         *message)
{
  static const RandValResponse init_value = RAND_VAL_RESPONSE__INIT;
  *message = init_value;
}
size_t rand_val_response__get_packed_size
                     (const RandValResponse *message)
{
  assert(message->base.descriptor == &rand_val_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rand_val_response__pack
                     (const RandValResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rand_val_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rand_val_response__pack_to_buffer
                     (const RandValResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rand_val_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RandValResponse *
       rand_val_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RandValResponse *)
     protobuf_c_message_unpack (&rand_val_response__descriptor,
                                allocator, len, data);
}
void   rand_val_response__free_unpacked
                     (RandValResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rand_val_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   status_request__init
                     (StatusRequest         *message)
{
  static const StatusRequest init_value = STATUS_REQUEST__INIT;
  *message = init_value;
}
size_t status_request__get_packed_size
                     (const StatusRequest *message)
{
  assert(message->base.descriptor == &status_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_request__pack
                     (const StatusRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_request__pack_to_buffer
                     (const StatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusRequest *
       status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusRequest *)
     protobuf_c_message_unpack (&status_request__descriptor,
                                allocator, len, data);
}
void   status_request__free_unpacked
                     (StatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   status_response__init
                     (StatusResponse         *message)
{
  static const StatusResponse init_value = STATUS_RESPONSE__INIT;
  *message = init_value;
}
size_t status_response__get_packed_size
                     (const StatusResponse *message)
{
  assert(message->base.descriptor == &status_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_response__pack
                     (const StatusResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_response__pack_to_buffer
                     (const StatusResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusResponse *
       status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusResponse *)
     protobuf_c_message_unpack (&status_response__descriptor,
                                allocator, len, data);
}
void   status_response__free_unpacked
                     (StatusResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_random_bytes_request__init
                     (GetRandomBytesRequest         *message)
{
  static const GetRandomBytesRequest init_value = GET_RANDOM_BYTES_REQUEST__INIT;
  *message = init_value;
}
size_t get_random_bytes_request__get_packed_size
                     (const GetRandomBytesRequest *message)
{
  assert(message->base.descriptor == &get_random_bytes_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_random_bytes_request__pack
                     (const GetRandomBytesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_random_bytes_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_random_bytes_request__pack_to_buffer
                     (const GetRandomBytesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_random_bytes_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetRandomBytesRequest *
       get_random_bytes_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetRandomBytesRequest *)
     protobuf_c_message_unpack (&get_random_bytes_request__descriptor,
                                allocator, len, data);
}
void   get_random_bytes_request__free_unpacked
                     (GetRandomBytesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_random_bytes_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   is_fully_seeded_response__init
                     (IsFullySeededResponse         *message)
{
  static const IsFullySeededResponse init_value = IS_FULLY_SEEDED_RESPONSE__INIT;
  *message = init_value;
}
size_t is_fully_seeded_response__get_packed_size
                     (const IsFullySeededResponse *message)
{
  assert(message->base.descriptor == &is_fully_seeded_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t is_fully_seeded_response__pack
                     (const IsFullySeededResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &is_fully_seeded_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t is_fully_seeded_response__pack_to_buffer
                     (const IsFullySeededResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &is_fully_seeded_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IsFullySeededResponse *
       is_fully_seeded_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IsFullySeededResponse *)
     protobuf_c_message_unpack (&is_fully_seeded_response__descriptor,
                                allocator, len, data);
}
void   is_fully_seeded_response__free_unpacked
                     (IsFullySeededResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &is_fully_seeded_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_seed_request__init
                     (GetSeedRequest         *message)
{
  static const GetSeedRequest init_value = GET_SEED_REQUEST__INIT;
  *message = init_value;
}
size_t get_seed_request__get_packed_size
                     (const GetSeedRequest *message)
{
  assert(message->base.descriptor == &get_seed_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_seed_request__pack
                     (const GetSeedRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_seed_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_seed_request__pack_to_buffer
                     (const GetSeedRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_seed_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSeedRequest *
       get_seed_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSeedRequest *)
     protobuf_c_message_unpack (&get_seed_request__descriptor,
                                allocator, len, data);
}
void   get_seed_request__free_unpacked
                     (GetSeedRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_seed_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drng_status_request__init
                     (DrngStatusRequest         *message)
{
  static const DrngStatusRequest init_value = DRNG_STATUS_REQUEST__INIT;
  *message = init_value;
}
size_t drng_status_request__get_packed_size
                     (const DrngStatusRequest *message)
{
  assert(message->base.descriptor == &drng_status_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drng_status_request__pack
                     (const DrngStatusRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drng_status_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drng_status_request__pack_to_buffer
                     (const DrngStatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drng_status_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DrngStatusRequest *
       drng_status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DrngStatusRequest *)
     protobuf_c_message_unpack (&drng_status_request__descriptor,
                                allocator, len, data);
}
void   drng_status_request__free_unpacked
                     (DrngStatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drng_status_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_data_request__init
                     (WriteDataRequest         *message)
{
  static const WriteDataRequest init_value = WRITE_DATA_REQUEST__INIT;
  *message = init_value;
}
size_t write_data_request__get_packed_size
                     (const WriteDataRequest *message)
{
  assert(message->base.descriptor == &write_data_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_data_request__pack
                     (const WriteDataRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_data_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_data_request__pack_to_buffer
                     (const WriteDataRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_data_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteDataRequest *
       write_data_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteDataRequest *)
     protobuf_c_message_unpack (&write_data_request__descriptor,
                                allocator, len, data);
}
void   write_data_request__free_unpacked
                     (WriteDataRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_data_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor val_response__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ValResponse, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ValResponse, val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned val_response__field_indices_by_name[] = {
  0,   /* field[0] = ret */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange val_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor val_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ValResponse",
  "ValResponse",
  "ValResponse",
  "",
  sizeof(ValResponse),
  2,
  val_response__field_descriptors,
  val_response__field_indices_by_name,
  1,  val_response__number_ranges,
  (ProtobufCMessageInit) val_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rand_val_response__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(RandValResponse, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "randval",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RandValResponse, randval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rand_val_response__field_indices_by_name[] = {
  1,   /* field[1] = randval */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange rand_val_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rand_val_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RandValResponse",
  "RandValResponse",
  "RandValResponse",
  "",
  sizeof(RandValResponse),
  2,
  rand_val_response__field_descriptors,
  rand_val_response__field_indices_by_name,
  1,  rand_val_response__number_ranges,
  (ProtobufCMessageInit) rand_val_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor status_request__field_descriptors[1] =
{
  {
    "maxlen",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatusRequest, maxlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_request__field_indices_by_name[] = {
  0,   /* field[0] = maxlen */
};
static const ProtobufCIntRange status_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor status_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatusRequest",
  "StatusRequest",
  "StatusRequest",
  "",
  sizeof(StatusRequest),
  1,
  status_request__field_descriptors,
  status_request__field_indices_by_name,
  1,  status_request__number_ranges,
  (ProtobufCMessageInit) status_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor status_response__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StatusResponse, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buffer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatusResponse, buffer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_response__field_indices_by_name[] = {
  1,   /* field[1] = buffer */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange status_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor status_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatusResponse",
  "StatusResponse",
  "StatusResponse",
  "",
  sizeof(StatusResponse),
  2,
  status_response__field_descriptors,
  status_response__field_indices_by_name,
  1,  status_response__number_ranges,
  (ProtobufCMessageInit) status_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_random_bytes_request__field_descriptors[1] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GetRandomBytesRequest, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_random_bytes_request__field_indices_by_name[] = {
  0,   /* field[0] = len */
};
static const ProtobufCIntRange get_random_bytes_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_random_bytes_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetRandomBytesRequest",
  "GetRandomBytesRequest",
  "GetRandomBytesRequest",
  "",
  sizeof(GetRandomBytesRequest),
  1,
  get_random_bytes_request__field_descriptors,
  get_random_bytes_request__field_indices_by_name,
  1,  get_random_bytes_request__number_ranges,
  (ProtobufCMessageInit) get_random_bytes_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor is_fully_seeded_response__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(IsFullySeededResponse, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fully_seeded",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(IsFullySeededResponse, fully_seeded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned is_fully_seeded_response__field_indices_by_name[] = {
  1,   /* field[1] = fully_seeded */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange is_fully_seeded_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor is_fully_seeded_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IsFullySeededResponse",
  "IsFullySeededResponse",
  "IsFullySeededResponse",
  "",
  sizeof(IsFullySeededResponse),
  2,
  is_fully_seeded_response__field_descriptors,
  is_fully_seeded_response__field_indices_by_name,
  1,  is_fully_seeded_response__number_ranges,
  (ProtobufCMessageInit) is_fully_seeded_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_seed_request__field_descriptors[2] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GetSeedRequest, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetSeedRequest, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_seed_request__field_indices_by_name[] = {
  1,   /* field[1] = flags */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange get_seed_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor get_seed_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSeedRequest",
  "GetSeedRequest",
  "GetSeedRequest",
  "",
  sizeof(GetSeedRequest),
  2,
  get_seed_request__field_descriptors,
  get_seed_request__field_indices_by_name,
  1,  get_seed_request__number_ranges,
  (ProtobufCMessageInit) get_seed_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drng_status_request__field_descriptors[3] =
{
  {
    "maxlen",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DrngStatusRequest, maxlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DrngStatusRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prediction_resistance",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DrngStatusRequest, prediction_resistance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drng_status_request__field_indices_by_name[] = {
  0,   /* field[0] = maxlen */
  1,   /* field[1] = node */
  2,   /* field[2] = prediction_resistance */
};
static const ProtobufCIntRange drng_status_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drng_status_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DrngStatusRequest",
  "DrngStatusRequest",
  "DrngStatusRequest",
  "",
  sizeof(DrngStatusRequest),
  3,
  drng_status_request__field_descriptors,
  drng_status_request__field_indices_by_name,
  1,  drng_status_request__number_ranges,
  (ProtobufCMessageInit) drng_status_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_data_request__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(WriteDataRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_data_request__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange write_data_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor write_data_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteDataRequest",
  "WriteDataRequest",
  "WriteDataRequest",
  "",
  sizeof(WriteDataRequest),
  1,
  write_data_request__field_descriptors,
  write_data_request__field_indices_by_name,
  1,  write_data_request__number_ranges,
  (ProtobufCMessageInit) write_data_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor unpriv_access__method_descriptors[15] =
{
  { "RpcStatus", &status_request__descriptor, &status_response__descriptor },
  { "RpcGetEntLvl", &empty_request__descriptor, &val_response__descriptor },
  { "RpcIsFullySeeded", &empty_request__descriptor, &is_fully_seeded_response__descriptor },
  { "RpcGetRandomBytesFull", &get_random_bytes_request__descriptor, &rand_val_response__descriptor },
  { "RpcGetRandomBytesPr", &get_random_bytes_request__descriptor, &rand_val_response__descriptor },
  { "RpcGetRandomBytes", &get_random_bytes_request__descriptor, &rand_val_response__descriptor },
  { "RpcGetSeed", &get_seed_request__descriptor, &rand_val_response__descriptor },
  { "RpcWriteData", &write_data_request__descriptor, &ret_response__descriptor },
  { "RpcRndGetEntCnt", &empty_request__descriptor, &val_response__descriptor },
  { "RpcGetPoolsize", &empty_request__descriptor, &val_response__descriptor },
  { "RpcGetWriteWakeupThresh", &empty_request__descriptor, &val_response__descriptor },
  { "RpcGetMinReseedSecs", &empty_request__descriptor, &val_response__descriptor },
  { "RpcJentStatus", &status_request__descriptor, &status_response__descriptor },
  { "RpcStatusJson", &status_request__descriptor, &status_response__descriptor },
  { "RpcDrngStatusJson", &drng_status_request__descriptor, &status_response__descriptor },
};
const unsigned unpriv_access__method_indices_by_name[] = {
  14,        /* RpcDrngStatusJson */
  1,        /* RpcGetEntLvl */
  11,        /* RpcGetMinReseedSecs */
  9,        /* RpcGetPoolsize */
  5,        /* RpcGetRandomBytes */
  3,        /* RpcGetRandomBytesFull */
  4,        /* RpcGetRandomBytesPr */
  6,        /* RpcGetSeed */
  10,        /* RpcGetWriteWakeupThresh */
  2,        /* RpcIsFullySeeded */
  12,        /* RpcJentStatus */
  8,        /* RpcRndGetEntCnt */
  0,        /* RpcStatus */
  13,        /* RpcStatusJson */
  7         /* RpcWriteData */
};
const ProtobufCServiceDescriptor unpriv_access__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "UnprivAccess",
  "UnprivAccess",
  "UnprivAccess",
  "",
  15,
  unpriv_access__method_descriptors,
  unpriv_access__method_indices_by_name
};
void unpriv_access__rpc_status(ProtobufCService *service,
                               const StatusRequest *input,
                               StatusResponse_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_ent_lvl(ProtobufCService *service,
                                    const EmptyRequest *input,
                                    ValResponse_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_is_fully_seeded(ProtobufCService *service,
                                        const EmptyRequest *input,
                                        IsFullySeededResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_random_bytes_full(ProtobufCService *service,
                                              const GetRandomBytesRequest *input,
                                              RandValResponse_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_random_bytes_pr(ProtobufCService *service,
                                            const GetRandomBytesRequest *input,
                                            RandValResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_random_bytes(ProtobufCService *service,
                                         const GetRandomBytesRequest *input,
                                         RandValResponse_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_seed(ProtobufCService *service,
                                 const GetSeedRequest *input,
                                 RandValResponse_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_write_data(ProtobufCService *service,
                                   const WriteDataRequest *input,
                                   RetResponse_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_rnd_get_ent_cnt(ProtobufCService *service,
                                        const EmptyRequest *input,
                                        ValResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_poolsize(ProtobufCService *service,
                                     const EmptyRequest *input,
                                     ValResponse_Closure closure,
                                     void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_write_wakeup_thresh(ProtobufCService *service,
                                                const EmptyRequest *input,
                                                ValResponse_Closure closure,
                                                void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 10, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_get_min_reseed_secs(ProtobufCService *service,
                                            const EmptyRequest *input,
                                            ValResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 11, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_jent_status(ProtobufCService *service,
                                    const StatusRequest *input,
                                    StatusResponse_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 12, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_status_json(ProtobufCService *service,
                                    const StatusRequest *input,
                                    StatusResponse_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 13, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__rpc_drng_status_json(ProtobufCService *service,
                                         const DrngStatusRequest *input,
                                         StatusResponse_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &unpriv_access__descriptor);
  service->invoke(service, 14, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unpriv_access__init (UnprivAccess_Service *service,
                          UnprivAccess_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &unpriv_access__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
