/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: unpriv_access.proto */

#ifndef PROTOBUF_C_unpriv_5faccess_2eproto__INCLUDED
#define PROTOBUF_C_unpriv_5faccess_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "common.pb-c.h"

typedef struct ValResponse ValResponse;
typedef struct RandValResponse RandValResponse;
typedef struct StatusRequest StatusRequest;
typedef struct StatusResponse StatusResponse;
typedef struct GetRandomBytesRequest GetRandomBytesRequest;
typedef struct IsFullySeededResponse IsFullySeededResponse;
typedef struct GetSeedRequest GetSeedRequest;
typedef struct DrngStatusRequest DrngStatusRequest;
typedef struct WriteDataRequest WriteDataRequest;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @brief Response carrying a return code plus a single unsigned value.
 * Used by the calls that report one counter or threshold (entropy level,
 * entropy count, poolsize, write wakeup threshold, min reseed seconds).
 * @param ret Return code (0 on success, < 0 on error)
 * @param val The reported value (semantics depend on the call)
 */
struct  ValResponse
{
  ProtobufCMessage base;
  int32_t ret;
  uint32_t val;
};
#define VAL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&val_response__descriptor) \
, 0, 0 }


/*
 **
 * @brief Response carrying a return code plus a byte payload.
 * Used by the random/seed generation calls. The fast-path encode/decode in
 * esdm_rpc_protocol.c relies on this exact { int64 ret = 1; bytes randval = 2; }
 * layout.
 * @param ret Return code of the generation request (>= 0 on success with the
 *	      value indicating the generated number of bytes, < -255 indicating
 *	      the maximum number of bytes that can be transferred in one
 *	      request, < 0 on error). For RpcGetSeed see esdm_get_seed.
 * @param randval Generated bytes
 */
struct  RandValResponse
{
  ProtobufCMessage base;
  int64_t ret;
  ProtobufCBinaryData randval;
};
#define RAND_VAL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rand_val_response__descriptor) \
, 0, {0,NULL} }


/*
 **
 * @brief Request to obtain status text.
 * Shared by RpcStatus, RpcStatusJson and RpcJentStatus.
 * A status text longer than maxlen is truncated. The calls rendering JSON
 * answer with -EMSGSIZE and an empty buffer instead: a document cut in half is
 * no JSON document, and a consumer receiving one cannot tell it from what the
 * ESDM meant to send.
 * @param maxlen Maximum size of buffer
 */
struct  StatusRequest
{
  ProtobufCMessage base;
  uint32_t maxlen;
};
#define STATUS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&status_request__descriptor) \
, 0 }


/*
 **
 * @brief Response carrying status text.
 * Shared by RpcStatus, RpcStatusJson and RpcJentStatus.
 * @param ret Return code (0 on success, < 0 on error); if no message buffer is
 *	      returned this value specifies the number of required bytes.
 * @param buffer Buffer with ASCII status - this is a NULL-terminated string
 */
struct  StatusResponse
{
  ProtobufCMessage base;
  int32_t ret;
  char *buffer;
};
#define STATUS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&status_response__descriptor) \
, 0, (char *)protobuf_c_empty_string }


/*
 **
 * @brief Request to get random bytes.
 * Shared by RpcGetRandomBytesFull, RpcGetRandomBytesPr and RpcGetRandomBytes.
 * @param len number of random bytes that are requested
 */
struct  GetRandomBytesRequest
{
  ProtobufCMessage base;
  uint64_t len;
};
#define GET_RANDOM_BYTES_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&get_random_bytes_request__descriptor) \
, 0 }


/*
 **
 * @brief Response to get fully seeded status
 * @param ret Return code (0 on success, < 0 on error)
 * @param fully_seeded fully seeded status (true if fully seeded,
 *					   false otherwise)
 */
struct  IsFullySeededResponse
{
  ProtobufCMessage base;
  int32_t ret;
  protobuf_c_boolean fully_seeded;
};
#define IS_FULLY_SEEDED_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&is_fully_seeded_response__descriptor) \
, 0, 0 }


/*
 **
 * @brief Request to get seed from entropy sources
 * @param len buffer size provided by caller
 * @param flags the flags field - see esdm_get_seed documentation
 */
struct  GetSeedRequest
{
  ProtobufCMessage base;
  uint64_t len;
  uint32_t flags;
};
#define GET_SEED_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&get_seed_request__descriptor) \
, 0, 0 }


/*
 **
 * @brief Request to obtain the status of a single DRNG instance.
 * The status document of RpcStatusJson reports the initial and the prediction
 * resistance DRNG only - the node instances follow the number of CPUs and
 * would outgrow the response on a large machine. They are obtained one at a
 * time with this request instead, addressed by the node they serve. A node
 * that has no instance is answered with -ENODEV, and a document that does not
 * fit into maxlen with -EMSGSIZE.
 * @param maxlen Maximum size of buffer
 * @param node Node whose DRNG instance is asked for, ignored when
 *	       prediction_resistance is set
 * @param prediction_resistance Ask for the prediction resistance instance,
 *				which is not bound to a node
 */
struct  DrngStatusRequest
{
  ProtobufCMessage base;
  uint32_t maxlen;
  uint32_t node;
  protobuf_c_boolean prediction_resistance;
};
#define DRNG_STATUS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&drng_status_request__descriptor) \
, 0, 0, 0 }


/*
 **
 * @brief Request to write data into the auxiliary entropy pool and perform an
 *	  immediate reseed.
 * @param data Buffer with the data to write into the DRNG - the entropy
 *	       estimator will remain unchanged.
 */
struct  WriteDataRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData data;
};
#define WRITE_DATA_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&write_data_request__descriptor) \
, {0,NULL} }


/* ValResponse methods */
void   val_response__init
                     (ValResponse         *message);
size_t val_response__get_packed_size
                     (const ValResponse   *message);
size_t val_response__pack
                     (const ValResponse   *message,
                      uint8_t             *out);
size_t val_response__pack_to_buffer
                     (const ValResponse   *message,
                      ProtobufCBuffer     *buffer);
ValResponse *
       val_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   val_response__free_unpacked
                     (ValResponse *message,
                      ProtobufCAllocator *allocator);
/* RandValResponse methods */
void   rand_val_response__init
                     (RandValResponse         *message);
size_t rand_val_response__get_packed_size
                     (const RandValResponse   *message);
size_t rand_val_response__pack
                     (const RandValResponse   *message,
                      uint8_t             *out);
size_t rand_val_response__pack_to_buffer
                     (const RandValResponse   *message,
                      ProtobufCBuffer     *buffer);
RandValResponse *
       rand_val_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rand_val_response__free_unpacked
                     (RandValResponse *message,
                      ProtobufCAllocator *allocator);
/* StatusRequest methods */
void   status_request__init
                     (StatusRequest         *message);
size_t status_request__get_packed_size
                     (const StatusRequest   *message);
size_t status_request__pack
                     (const StatusRequest   *message,
                      uint8_t             *out);
size_t status_request__pack_to_buffer
                     (const StatusRequest   *message,
                      ProtobufCBuffer     *buffer);
StatusRequest *
       status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   status_request__free_unpacked
                     (StatusRequest *message,
                      ProtobufCAllocator *allocator);
/* StatusResponse methods */
void   status_response__init
                     (StatusResponse         *message);
size_t status_response__get_packed_size
                     (const StatusResponse   *message);
size_t status_response__pack
                     (const StatusResponse   *message,
                      uint8_t             *out);
size_t status_response__pack_to_buffer
                     (const StatusResponse   *message,
                      ProtobufCBuffer     *buffer);
StatusResponse *
       status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   status_response__free_unpacked
                     (StatusResponse *message,
                      ProtobufCAllocator *allocator);
/* GetRandomBytesRequest methods */
void   get_random_bytes_request__init
                     (GetRandomBytesRequest         *message);
size_t get_random_bytes_request__get_packed_size
                     (const GetRandomBytesRequest   *message);
size_t get_random_bytes_request__pack
                     (const GetRandomBytesRequest   *message,
                      uint8_t             *out);
size_t get_random_bytes_request__pack_to_buffer
                     (const GetRandomBytesRequest   *message,
                      ProtobufCBuffer     *buffer);
GetRandomBytesRequest *
       get_random_bytes_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   get_random_bytes_request__free_unpacked
                     (GetRandomBytesRequest *message,
                      ProtobufCAllocator *allocator);
/* IsFullySeededResponse methods */
void   is_fully_seeded_response__init
                     (IsFullySeededResponse         *message);
size_t is_fully_seeded_response__get_packed_size
                     (const IsFullySeededResponse   *message);
size_t is_fully_seeded_response__pack
                     (const IsFullySeededResponse   *message,
                      uint8_t             *out);
size_t is_fully_seeded_response__pack_to_buffer
                     (const IsFullySeededResponse   *message,
                      ProtobufCBuffer     *buffer);
IsFullySeededResponse *
       is_fully_seeded_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   is_fully_seeded_response__free_unpacked
                     (IsFullySeededResponse *message,
                      ProtobufCAllocator *allocator);
/* GetSeedRequest methods */
void   get_seed_request__init
                     (GetSeedRequest         *message);
size_t get_seed_request__get_packed_size
                     (const GetSeedRequest   *message);
size_t get_seed_request__pack
                     (const GetSeedRequest   *message,
                      uint8_t             *out);
size_t get_seed_request__pack_to_buffer
                     (const GetSeedRequest   *message,
                      ProtobufCBuffer     *buffer);
GetSeedRequest *
       get_seed_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   get_seed_request__free_unpacked
                     (GetSeedRequest *message,
                      ProtobufCAllocator *allocator);
/* DrngStatusRequest methods */
void   drng_status_request__init
                     (DrngStatusRequest         *message);
size_t drng_status_request__get_packed_size
                     (const DrngStatusRequest   *message);
size_t drng_status_request__pack
                     (const DrngStatusRequest   *message,
                      uint8_t             *out);
size_t drng_status_request__pack_to_buffer
                     (const DrngStatusRequest   *message,
                      ProtobufCBuffer     *buffer);
DrngStatusRequest *
       drng_status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   drng_status_request__free_unpacked
                     (DrngStatusRequest *message,
                      ProtobufCAllocator *allocator);
/* WriteDataRequest methods */
void   write_data_request__init
                     (WriteDataRequest         *message);
size_t write_data_request__get_packed_size
                     (const WriteDataRequest   *message);
size_t write_data_request__pack
                     (const WriteDataRequest   *message,
                      uint8_t             *out);
size_t write_data_request__pack_to_buffer
                     (const WriteDataRequest   *message,
                      ProtobufCBuffer     *buffer);
WriteDataRequest *
       write_data_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   write_data_request__free_unpacked
                     (WriteDataRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ValResponse_Closure)
                 (const ValResponse *message,
                  void *closure_data);
typedef void (*RandValResponse_Closure)
                 (const RandValResponse *message,
                  void *closure_data);
typedef void (*StatusRequest_Closure)
                 (const StatusRequest *message,
                  void *closure_data);
typedef void (*StatusResponse_Closure)
                 (const StatusResponse *message,
                  void *closure_data);
typedef void (*GetRandomBytesRequest_Closure)
                 (const GetRandomBytesRequest *message,
                  void *closure_data);
typedef void (*IsFullySeededResponse_Closure)
                 (const IsFullySeededResponse *message,
                  void *closure_data);
typedef void (*GetSeedRequest_Closure)
                 (const GetSeedRequest *message,
                  void *closure_data);
typedef void (*DrngStatusRequest_Closure)
                 (const DrngStatusRequest *message,
                  void *closure_data);
typedef void (*WriteDataRequest_Closure)
                 (const WriteDataRequest *message,
                  void *closure_data);

/* --- services --- */

typedef struct UnprivAccess_Service UnprivAccess_Service;
struct UnprivAccess_Service
{
  ProtobufCService base;
  void (*rpc_status)(UnprivAccess_Service *service,
                     const StatusRequest *input,
                     StatusResponse_Closure closure,
                     void *closure_data);
  void (*rpc_get_ent_lvl)(UnprivAccess_Service *service,
                          const EmptyRequest *input,
                          ValResponse_Closure closure,
                          void *closure_data);
  void (*rpc_is_fully_seeded)(UnprivAccess_Service *service,
                              const EmptyRequest *input,
                              IsFullySeededResponse_Closure closure,
                              void *closure_data);
  void (*rpc_get_random_bytes_full)(UnprivAccess_Service *service,
                                    const GetRandomBytesRequest *input,
                                    RandValResponse_Closure closure,
                                    void *closure_data);
  void (*rpc_get_random_bytes_pr)(UnprivAccess_Service *service,
                                  const GetRandomBytesRequest *input,
                                  RandValResponse_Closure closure,
                                  void *closure_data);
  void (*rpc_get_random_bytes)(UnprivAccess_Service *service,
                               const GetRandomBytesRequest *input,
                               RandValResponse_Closure closure,
                               void *closure_data);
  void (*rpc_get_seed)(UnprivAccess_Service *service,
                       const GetSeedRequest *input,
                       RandValResponse_Closure closure,
                       void *closure_data);
  void (*rpc_write_data)(UnprivAccess_Service *service,
                         const WriteDataRequest *input,
                         RetResponse_Closure closure,
                         void *closure_data);
  void (*rpc_rnd_get_ent_cnt)(UnprivAccess_Service *service,
                              const EmptyRequest *input,
                              ValResponse_Closure closure,
                              void *closure_data);
  void (*rpc_get_poolsize)(UnprivAccess_Service *service,
                           const EmptyRequest *input,
                           ValResponse_Closure closure,
                           void *closure_data);
  void (*rpc_get_write_wakeup_thresh)(UnprivAccess_Service *service,
                                      const EmptyRequest *input,
                                      ValResponse_Closure closure,
                                      void *closure_data);
  void (*rpc_get_min_reseed_secs)(UnprivAccess_Service *service,
                                  const EmptyRequest *input,
                                  ValResponse_Closure closure,
                                  void *closure_data);
  void (*rpc_jent_status)(UnprivAccess_Service *service,
                          const StatusRequest *input,
                          StatusResponse_Closure closure,
                          void *closure_data);
  void (*rpc_status_json)(UnprivAccess_Service *service,
                          const StatusRequest *input,
                          StatusResponse_Closure closure,
                          void *closure_data);
  void (*rpc_drng_status_json)(UnprivAccess_Service *service,
                               const DrngStatusRequest *input,
                               StatusResponse_Closure closure,
                               void *closure_data);
};
typedef void (*UnprivAccess_ServiceDestroy)(UnprivAccess_Service *);
void unpriv_access__init (UnprivAccess_Service *service,
                          UnprivAccess_ServiceDestroy destroy);
#define UNPRIV_ACCESS__BASE_INIT \
    { &unpriv_access__descriptor, protobuf_c_service_invoke_internal, NULL }
#define UNPRIV_ACCESS__INIT(function_prefix__) \
    { UNPRIV_ACCESS__BASE_INIT,\
      function_prefix__ ## rpc_status,\
      function_prefix__ ## rpc_get_ent_lvl,\
      function_prefix__ ## rpc_is_fully_seeded,\
      function_prefix__ ## rpc_get_random_bytes_full,\
      function_prefix__ ## rpc_get_random_bytes_pr,\
      function_prefix__ ## rpc_get_random_bytes,\
      function_prefix__ ## rpc_get_seed,\
      function_prefix__ ## rpc_write_data,\
      function_prefix__ ## rpc_rnd_get_ent_cnt,\
      function_prefix__ ## rpc_get_poolsize,\
      function_prefix__ ## rpc_get_write_wakeup_thresh,\
      function_prefix__ ## rpc_get_min_reseed_secs,\
      function_prefix__ ## rpc_jent_status,\
      function_prefix__ ## rpc_status_json,\
      function_prefix__ ## rpc_drng_status_json  }
void unpriv_access__rpc_status(ProtobufCService *service,
                               const StatusRequest *input,
                               StatusResponse_Closure closure,
                               void *closure_data);
void unpriv_access__rpc_get_ent_lvl(ProtobufCService *service,
                                    const EmptyRequest *input,
                                    ValResponse_Closure closure,
                                    void *closure_data);
void unpriv_access__rpc_is_fully_seeded(ProtobufCService *service,
                                        const EmptyRequest *input,
                                        IsFullySeededResponse_Closure closure,
                                        void *closure_data);
void unpriv_access__rpc_get_random_bytes_full(ProtobufCService *service,
                                              const GetRandomBytesRequest *input,
                                              RandValResponse_Closure closure,
                                              void *closure_data);
void unpriv_access__rpc_get_random_bytes_pr(ProtobufCService *service,
                                            const GetRandomBytesRequest *input,
                                            RandValResponse_Closure closure,
                                            void *closure_data);
void unpriv_access__rpc_get_random_bytes(ProtobufCService *service,
                                         const GetRandomBytesRequest *input,
                                         RandValResponse_Closure closure,
                                         void *closure_data);
void unpriv_access__rpc_get_seed(ProtobufCService *service,
                                 const GetSeedRequest *input,
                                 RandValResponse_Closure closure,
                                 void *closure_data);
void unpriv_access__rpc_write_data(ProtobufCService *service,
                                   const WriteDataRequest *input,
                                   RetResponse_Closure closure,
                                   void *closure_data);
void unpriv_access__rpc_rnd_get_ent_cnt(ProtobufCService *service,
                                        const EmptyRequest *input,
                                        ValResponse_Closure closure,
                                        void *closure_data);
void unpriv_access__rpc_get_poolsize(ProtobufCService *service,
                                     const EmptyRequest *input,
                                     ValResponse_Closure closure,
                                     void *closure_data);
void unpriv_access__rpc_get_write_wakeup_thresh(ProtobufCService *service,
                                                const EmptyRequest *input,
                                                ValResponse_Closure closure,
                                                void *closure_data);
void unpriv_access__rpc_get_min_reseed_secs(ProtobufCService *service,
                                            const EmptyRequest *input,
                                            ValResponse_Closure closure,
                                            void *closure_data);
void unpriv_access__rpc_jent_status(ProtobufCService *service,
                                    const StatusRequest *input,
                                    StatusResponse_Closure closure,
                                    void *closure_data);
void unpriv_access__rpc_status_json(ProtobufCService *service,
                                    const StatusRequest *input,
                                    StatusResponse_Closure closure,
                                    void *closure_data);
void unpriv_access__rpc_drng_status_json(ProtobufCService *service,
                                         const DrngStatusRequest *input,
                                         StatusResponse_Closure closure,
                                         void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor val_response__descriptor;
extern const ProtobufCMessageDescriptor rand_val_response__descriptor;
extern const ProtobufCMessageDescriptor status_request__descriptor;
extern const ProtobufCMessageDescriptor status_response__descriptor;
extern const ProtobufCMessageDescriptor get_random_bytes_request__descriptor;
extern const ProtobufCMessageDescriptor is_fully_seeded_response__descriptor;
extern const ProtobufCMessageDescriptor get_seed_request__descriptor;
extern const ProtobufCMessageDescriptor drng_status_request__descriptor;
extern const ProtobufCMessageDescriptor write_data_request__descriptor;
extern const ProtobufCServiceDescriptor unpriv_access__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_unpriv_5faccess_2eproto__INCLUDED */
