name: ESDM Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libprotobuf-c-dev
    - name: Install Jitter RNG
    - run: wget -O jent.tar.gz https://github.com/smuellerDD/jitterentropy-library/archive/refs/tags/v3.4.1.tar.gz
    - run: tar xvfz jent.tar.gz
    - run: make -C jitterentropy-library*
    - run: sudo make -C jitterentropy-library* install
    - name: Meson setup
      run: meson setup build -Dtestmode=enabled -Dselinux=disabled
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: sudo meson test -C build
