name: ESDM Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libprotobuf-c-dev libfuse3-dev
    - name: Install Jitter RNG
      run: |
        wget -O jent.tar.gz https://github.com/smuellerDD/jitterentropy-library/archive/refs/tags/v3.4.1.tar.gz
        tar xvfz jent.tar.gz
        make -C jitterentropy-library*
        sudo make -C jitterentropy-library* install
        sudo ldconfig
    - name: Meson setup
      run: meson setup build -Dtestmode=enabled -Dselinux=disabled -Dais2031=false -Dsp80090c=true
    - name: Meson compile
      run: meson compile -C build

# TODO: invoke meson test with real root privileges to enable all CUSE tests
    - name: Meson test
      run: meson test -v -C build
